/**
 * ExerciseFormPlayer
 * ---------------------------------------------------------------------------
 * Shared shell used by Squat, PushUp, PullUp and SitUp. Renders the animated
 * stick figure plus the controls around it: side/front toggle, "correct form
 * vs. common mistake" picker, play/pause + scrubber, indicator checkboxes,
 * live metric cards and a coaching caption.
 *
 * You normally won't use this directly; import an exercise component instead.
 * It only needs data in the shape exported by each `*Form.js` file.
 *
 * Data source: static, bundled with the app. No API calls.
 *
 * @param {Object} props
 * @param {string} props.title - Accessible name, e.g. "Push-up".
 * @param {string[]} props.phases - Four labels: start, down, hold, return.
 * @param {Object} props.views - `{ side, front }`, each `{ draw, desc, modes, inds, good, bad }`.
 * @param {"side"|"front"} [props.defaultView="side"]
 * @param {boolean} [props.autoPlay=true]
 * @param {number} [props.duration=6500] - ms per rep loop.
 * @param {boolean} [props.showTitle=false] - Show the title as a visible heading.
 * @param {boolean} [props.showViewToggle=true] - Side/front buttons.
 * @param {boolean} [props.showMistakes=true] - "Form to show" dropdown.
 * @param {boolean} [props.showIndicators=true] - Indicator checkboxes.
 * @param {boolean} [props.showMetrics=true] - Live metric cards.
 * @param {boolean} [props.showControls=true] - Play/pause button and scrubber.
 * @param {boolean} [props.showFeedback=true] - Phase chip + coaching caption.
 * @param {number} [props.startAt=0] - Initial loop position (0-1).
 * @param {string} [props.className]
 */

import { useId, useState } from "react";
import "./ExerciseFormGuide.css";
import useExerciseAnimation from "./useExerciseAnimation.js";
import { phaseIndex, tOf } from "./svgKit.js";

const VIEW_LABELS = { side: "Side view", front: "Front view" };

function PlayIcon() {
  return (
    <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
      <path d="M7 4.5v15l12-7.5z" fill="currentColor" />
    </svg>
  );
}

function PauseIcon() {
  return (
    <svg viewBox="0 0 24 24" width="16" height="16" aria-hidden="true">
      <path d="M6 4h4v16H6zM14 4h4v16h-4z" fill="currentColor" />
    </svg>
  );
}

export default function ExerciseFormPlayer({
  title,
  phases,
  views,
  defaultView = "side",
  autoPlay = true,
  duration = 6500,
  showTitle = false,
  showViewToggle = true,
  showMistakes = true,
  showIndicators = true,
  showMetrics = true,
  showControls = true,
  showFeedback = true,
  startAt = 0,
  className = "",
}) {
  const uid = useId();
  const viewKeys = Object.keys(views);
  const [view, setView] = useState(views[defaultView] ? defaultView : viewKeys[0]);
  const [mode, setMode] = useState("good");
  const [on, setOn] = useState(() =>
    Object.fromEntries(viewKeys.flatMap((v) => views[v].inds.map(([key]) => [key, true]))),
  );
  const { p, playing, toggle, scrub } = useExerciseAnimation({ autoPlay, duration, startAt });

  const cfg = views[view];
  const t = tOf(p);
  const frame = cfg.draw(t, { mode, on, p });
  const phase = phaseIndex(t, p);
  const isGood = mode === "good";
  const goodTone = frame.ok ?? frame.goodDepth;
  const chipTone = isGood ? (goodTone ? "good" : "info") : "bad";

  const changeView = (next) => {
    setView(next);
    setMode("good");
  };

  return (
    <section className={`fg ${className}`.trim()} aria-label={`${title} form guide`}>
      <h3 className={showTitle ? "fg-title" : "fg-sr-only"}>{title}</h3>

      {((showViewToggle && viewKeys.length > 1) || showMistakes) && (
        <div className="fg-row">
          {showViewToggle && viewKeys.length > 1 && (
            <div className="fg-row" role="group" aria-label="Camera angle">
              {viewKeys.map((v) => (
                <button
                  key={v}
                  type="button"
                  className="fg-seg"
                  aria-pressed={v === view}
                  onClick={() => changeView(v)}
                >
                  {VIEW_LABELS[v] ?? v}
                </button>
              ))}
            </div>
          )}
          {showMistakes && (
            <select
              className="fg-select"
              aria-label="Form to show"
              value={mode}
              onChange={(e) => setMode(e.target.value)}
            >
              {cfg.modes.map(([key, label]) => (
                <option key={key} value={key}>{label}</option>
              ))}
            </select>
          )}
        </div>
      )}

      <svg className="fg-svg" viewBox="0 0 680 392" role="img" aria-labelledby={`${uid}-t ${uid}-d`}>
        <title id={`${uid}-t`}>{title} form animation</title>
        <desc id={`${uid}-d`}>{cfg.desc}</desc>
        {/* SVG markup is generated by our own draw functions from numbers and constant strings only. */}
        <g dangerouslySetInnerHTML={{ __html: frame.svg }} />
      </svg>

      {showControls && (
        <div className="fg-controls">
          <button
            type="button"
            className="fg-play"
            aria-label={playing ? "Pause" : "Play"}
            onClick={toggle}
          >
            {playing ? <PauseIcon /> : <PlayIcon />}
          </button>
          <input
            type="range"
            className="fg-range"
            min="0"
            max="1000"
            step="1"
            value={Math.round(p * 1000)}
            aria-label={`${title} position`}
            onChange={(e) => scrub(e.target.value / 1000)}
          />
          <span className="fg-phase">{phases[phase]}</span>
        </div>
      )}

      {showIndicators && (
        <div className="fg-indicators">
          {cfg.inds.map(([key, label]) => (
            <label key={key} className="fg-indicator">
              <input
                type="checkbox"
                checked={!!on[key]}
                onChange={(e) => setOn((prev) => ({ ...prev, [key]: e.target.checked }))}
              />
              {label}
            </label>
          ))}
        </div>
      )}

      {showMetrics && (
        <div className="fg-metrics">
          {frame.cards.map(([label, value, tone]) => (
            <div key={label} className="fg-metric">
              <p className="fg-metric-label">{label}</p>
              <p className={`fg-metric-value${tone ? ` fg-metric-value--${tone}` : ""}`}>{value}</p>
            </div>
          ))}
        </div>
      )}

      {showFeedback && (
        <div className="fg-feedback">
          <span className={`fg-chip fg-chip--${chipTone}`}>
            {isGood ? phases[phase] : cfg.bad[mode][0]}
          </span>
          <span className="fg-msg">{isGood ? cfg.good[phase] : cfg.bad[mode][1]}</span>
        </div>
      )}
    </section>
  );
}